wandb: WARNING Step cannot be set when using syncing with tensorboard. Please log your step values as a metric such as 'global_step'
Traceback (most recent call last):
  File "C:\Users\Jack-Server\.conda\envs\testenv2\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-fa001381000b>", line 1, in <module>
    runfile('C:/Users/Jack-Server/Documents/GitHub/PhD/Modern Implementations/DQN_etc/DQN_Classes.py', wdir='C:/Users/Jack-Server/Documents/GitHub/PhD/Modern Implementations/DQN_etc')
  File "C:\Users\Jack-Server\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\212.5080.64\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Users\Jack-Server\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\212.5080.64\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Jack-Server/Documents/GitHub/PhD/Modern Implementations/DQN_etc/DQN_Classes.py", line 272, in <module>
    train_h_DQN(env,meta_model,model,meta_replay_buffer,replay_buffer,
  File "C:/Users/Jack-Server/Documents/GitHub/PhD/Modern Implementations/DQN_etc/DQN_Classes.py", line 192, in train_h_DQN
    train_log(metric_name,loss,frame_idx)
NameError: name 'loss' is not defined
1
12
12
Logging reward of: 28.0, at frame index: 29, to WandB
29
30
38
